- name: test playbook
  hosts: localhost
  tasks:
    - debug:
        msg: "dsadasdasdasndasndadjlnajkndaskjndkasjndkjsandkjsnjskdnsdjkcnasdkjacnskjncskajcanskjnsakdjncskajcnaskjcnsakjcn jdsbjsdcsd jcdjhb"  
