dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
lint: |
  set -e
  yamllint .
  ansible-lint $PWD/*
  flake8

platforms:
  - name: custom-delegated
provisioner:
  name: ansible
  lint: |
    set -e
    yamllint .
    ansible-lint .
    flake8
  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
    prepare: prepare.yml
    cleanup: cleanup.yml
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: ansible
  options:
    # Add a -v so you see the individual test names,
    # particularly useful with parameterized tests
    v: true
  lint: |
    set -e
    yamllint .
    ansible-lint .
    flake8
